### ISSUE TITLE
Consider marking references to Cake.Core and Cake.Common as private

### ISSUE THREAD

**Issue by augustoproiete** [lprichar/Cake.AzureCli#1]
Hey Lee, just saw your announcement on Twitter and thought I'd leave you note here:

[![image](https://user-images.githubusercontent.com/177608/108102501-ff749800-705e-11eb-86d7-883cf67e3caf.png)](https://www.nuget.org/packages/Cake.AzureCli/)

`Cake.Core` and `Cake.Common` are already loaded in the Cake runner, thus declaring these NuGet packages as dependencies is not necessary (no need for the nuget packages to be downloaded, and the runner won't be able to load the assemblies anyway)

It's documented here: https://cakebuild.net/docs/extending/addins/best-practices#cake-reference

[![image](https://user-images.githubusercontent.com/177608/108102509-026f8880-705f-11eb-9c0c-313ff4857dd9.png)](https://cakebuild.net/docs/extending/addins/best-practices#cake-reference)

**Comment by lprichar** [comment]
✅ thanks for the heads up @augustoproiete
